### ISSUE TITLE
could not find function "%.%

### ISSUE THREAD

**Issue by robbig2871** [jcheng5/superzip#5]
shiny::runGitHub("superzip", "jcheng5")
Downloading https://github.com/jcheng5/superzip/archive/master.tar.gz
Error in ..stacktraceon..({ : could not find function "%.%"

**Comment by jmolayem** [comment]
I got the same error: Error in ..stacktraceon..({ : could not find function "%.%

**Comment by jmolayem** [comment]
Nevermind. This was solved by a previous issue: Change %.% to %>%

**Comment by trebuchet90** [comment]
I still have this error even though there is no "%.%" anywhere in the code. everything is %>%. any ideas?

**Comment by jcheng5** [comment]
Please try https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example instead. Thanks.
